---

- hosts: all
  become: true
  tasks:

  - name: Ubuntu update reposotory index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Ubuntu install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Ubuntu install php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: CentOS update reposotory index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: CentOS install apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: CentOS install php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"

